"""empty message

Revision ID: 9b730cb5094d
Revises: 59c31bb24ef8
Create Date: 2023-07-20 19:18:07.566781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b730cb5094d'
down_revision = '59c31bb24ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tributos', schema=None) as batch_op:
        batch_op.drop_constraint('c_img_src', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tributos', schema=None) as batch_op:
        batch_op.create_unique_constraint('c_img_src', ['img_src'])

    # ### end Alembic commands ###
